Add deadline to flyte grpc client
spotify/styx pull request #1069
Opened 2023-04-14 15:06 UTC by pablocasares

# Hey, I just made a Pull Request!

## Description

Add a deadline for grpc flyte client calls.

## Motivation and Context

This change is required to avoid Styx keeping broken connections for a long time generating a thread starvation problem. 

## Have you tested this? If so, how?
 

## Checklist for PR author(s)

- [ ] Changes are covered by unit test
- [ ] All tests pass
- [ ] Code coverage check passes
- [ ] Error handling is tested
- [ ] Errors are handled at the appropriate layer
- [ ] Errors that cannot be handled where they occur are propagated
- [ ] (optional) Changes are covered by system test
- [ ] Relevant documentation updated
- [ ] This PR has NO breaking change to public API
- [ ] This PR has breaking change to public API and it is documented

## Checklist for PR reviewer(s)

- [ ] This PR has been incorporated in release note for the coming version
- [ ] Risky changes introduced by this PR have been all considered

2023-04-14 15:07 UTC, pablocasares commented on styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
> +        AdminServiceGrpc.newBlockingStub(channel).withDeadlineAfter(GRPC_CALL_DEADLINE_SECONDS, TimeUnit.SECONDS));
This is where the Deadline has been added.

2023-04-17 07:07 UTC, sonjaer commented on styx-flyte-client/src/main/java/com/spotify/styx/flyte/client/FlyteAdminClient.java
> +  private static final int GRPC_CALL_DEADLINE_SECONDS = 5;
Since the release cycles are so long, maybe we can refactor this to a config?

2023-04-17 12:34 UTC, sonjaer approved these changes

2023-04-17 12:38 UTC, sonjaer requested changes
hmm, let me double check smth

2023-04-17 12:41 UTC, sonjaer commented on styx-scheduler-service/src/test/java/com/spotify/styx/StyxSchedulerTest.java
> +        .put("styx.flyte.admin.production.grpc.max-retry-attempts", "3");
I don't think we should have production here?

2023-04-17 13:42 UTC, sonjaer approved these changes

2023-04-17 13:54 UTC, merged